version: '3.8'

services:
  # Service for the Ruby on Rails web application
  api:
    build: .  # Build the service's image from the current directory
    command: bundle exec rails s -p 3000 -b '0.0.0.0'  # Command to start the Rails server
    ports:
      - "3000:3000"  # Expose ports for accessing the application
    volumes:
      - .:/app  # Mount the current directory inside the container
    depends_on:
      - db
      - cache
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - CHATGPT_KEY=${CHATGPT_KEY}
      - LEONARDO_KEY=${LEONARDO_KEY}
      - JSON2VIDEO_KEY=${JSON2VIDEO_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_ACCESS_SECRET=${AWS_ACCESS_SECRET}
      - ELEVENLABS_KEY=${ELEVENLABS_KEY}
    networks:
      - some-net

  # Service for the PostgreSQL database
  db:
    image: postgres:13  # Use the official PostgreSQL version 13 image
    ports:
      - "5432:5432"  # Expose port for accessing the database
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Create a volume for storing database data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=${REDIS_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: "postgres"
    networks:
      - some-net
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes: 
      - ./cache:/data
    networks:
      - some-net

# Define a volume for storing PostgreSQL data
volumes:
  postgres_data:

networks:
  some-net:
    driver: bridge